###########################################################################
# Population genetics reveals insights into Cryophytum} biogeography in South Africa
# van Steenderen, C.J.M., Sandenbergh, E., and Paterson, I.D. 2026
# Ecology and Evolution

# This script filters the SNP output from Stacks
###########################################################################

source("setup.R")

###########################################################################
# FILTERING THE SNP OUTPUT FROM STACKS
# using the SNPfiltR package
##########################################################################

all.snps = vcfR::read.vcfR("data/populations.snps.vcf")

popmap = read.table("data/bothplates_pops_refgenome.txt", header = F, sep = "\t")
head(popmap)
colnames(popmap) = c("id", "pop")

#visualise
SNPfiltR::hard_filter(vcfR=all.snps)

# ***** Object of Class vcfR *****
# 136 samples
# 13220 CHROMs
# 156,260 variants
# Object size: 736.9 Mb
# 45.35 percent missing data
# *****        *****         *****

all.snps = SNPfiltR::hard_filter(vcfR=all.snps, depth = 5, gq = 35)
all.snps = SNPfiltR::filter_allele_balance(all.snps)

# dashed line indicates a mean depth across all SNPs of 37.2
SNPfiltR::max_depth(all.snps)

all.snps = SNPfiltR::max_depth(all.snps, maxdepth = 100)
all.snps

SNPfiltR::missing_by_sample(vcfR=all.snps, popmap = popmap)

# 6 samples are above a 0.9 missing data cutoff, and were removed from VCF
all.snps = SNPfiltR::missing_by_sample(vcfR=all.snps, cutoff = .9)

#subset popmap to only include retained individuals
popmap = popmap[popmap$id %in% colnames(all.snps@gt),]

#remove invariant sites generated by dropping individuals
all.snps = SNPfiltR::min_mac(all.snps, min.mac = 3)

miss = SNPfiltR::assess_missing_data_pca(vcfR=all.snps, 
            popmap = popmap, thresholds = .8, clustering = FALSE)

# Picking joint bandwidth of 0.0483
SNPfiltR::missing_by_snp(all.snps)

miss = SNPfiltR::assess_missing_data_pca(vcfR=all.snps, popmap = popmap, 
                        thresholds = c(.6, .65, .7), clustering = FALSE)

all.snps = SNPfiltR::missing_by_snp(all.snps, cutoff = .80)

all.snps

all.snps.mac = SNPfiltR::min_mac(vcfR = all.snps, min.mac = 2)

#assess clustering without MAC cutoff
miss = SNPfiltR::assess_missing_data_tsne(all.snps, popmap, 
                                          clustering = FALSE)
#assess clustering with MAC cutoff
miss = SNPfiltR::assess_missing_data_tsne(all.snps.mac, popmap, 
                                          clustering = FALSE)

#plot depth per snp and per sample
dp = vcfR::extract.gt(all.snps, element = "DP", as.numeric=TRUE)
vcfR::heatmap.bp(dp, rlabels = FALSE)

#plot genotype quality per snp and per sample
gq = vcfR::extract.gt(all.snps, element = "GQ", as.numeric=TRUE)
vcfR::heatmap.bp(gq, rlabels = FALSE)

all.snps

# original file: 136 samples, 156,260 SNPs
# after filtering: 130 samples, 27,587 SNPs (8.5% missing data)
# ~6X smaller

vcfR::write.vcf(all.snps, "data/populations.snps.filtered_mac3.vcf")

# convert to genind
all.snps_genind = vcfR::vcfR2genind(all.snps)
all.snps_genind

# convert to genlight
all.snps_genlight = vcfR::vcfR2genlight(all.snps)
genlight_sample_names = as.data.frame(all.snps_genlight@ind.names)
colnames(genlight_sample_names) = "sample_id"
head(genlight_sample_names)

###########################################################################
# PCA
##########################################################################

# broad_myCol = c("gold", "red", "forestgreen")

all.snps = vcfR::read.vcfR("data/populations.snps.filtered_mac3.vcf")
all.snps_genlight = vcfR::vcfR2genlight(all.snps)
genlight_sample_names = as.data.frame(all.snps_genlight@ind.names)
colnames(genlight_sample_names) = "sample_id"

###################################
# STANDARD PCA
###################################

sample.info = readxl::read_excel("data/RADseq_sample_info.xlsx", sheet = 1) %>%
  janitor::clean_names()

head(sample.info)
names(sample.info)
str(sample.info)

sample.info$sample_id = trimws(sample.info$sample_id)
genlight_sample_names$sample_id = trimws(genlight_sample_names$sample_id)

filtered_info = sample.info %>%
  dplyr::filter(sample_id %in% genlight_sample_names$sample_id)

# Reorder to match genlight_sample_names
filtered_info = filtered_info %>%
  dplyr::slice(match(genlight_sample_names$sample_id, sample_id))


str(filtered_info)

PCA = adegenet::glPca(all.snps_genlight, nf = 10)

# Extract PCA scores
scores = as.data.frame(PCA$scores)  # PCA coordinates (individuals × axes)
scores$group = filtered_info$identity

head(scores)

# Remove rows where the rowname contains "USA" or "MX"
scores = scores[
  (grepl("SA", rownames(scores)) | grepl("OUSA", rownames(scores))) &
    !grepl("^USA", rownames(scores)) &  # Exclude names starting with USA
    !grepl("MX", rownames(scores)),     # Exclude anything with MX
]

all.snps_genlight@ind.names
samples_to_remove = rownames(scores)

####################################
# PCA

pca.ggplot = ggplot(scores, aes(x = PC1, y = PC2, fill = group)) +
  
  ggrepel::geom_text_repel(aes(label = rownames(scores)), 
                           vjust = -1.5, size = 2.5, colour = "black",
                           segment.color = "grey80",
                           max.overlaps = 50) +
  geom_point(alpha = 1, size = 3, shape = 21) +
  labs(
    #title = "PCA of RADseq data - ref genome assembly",
    x = paste0("PC1 (", round(PCA$eig[1] / sum(PCA$eig) * 100, 1), "%)"),
    y = paste0("PC2 (", round(PCA$eig[2] / sum(PCA$eig) * 100, 1), "%)")
  ) +
  scale_fill_manual(values = c(
   "gold",
    "red",
    "forestgreen",
    "blue",
    "lightblue"
  )) +
  theme_classic() +
  theme(legend.position = "right") +
  #ggtitle("d)") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey50") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50")

pca.ggplot

# ggsave("figures/pca.png", pca.ggplot, width = 12, dpi=400,
#        height = 7, units = "in")
# ggsave("figures/pca.svg", pca.ggplot, width = 11, dpi=400,
#        height = 7, units = "in")

#################################################################
# MAP OF SA
#################################################################

gps.points = readxl::read_excel("data/RADseq_sample_info.xlsx",
                                 sheet = 1) %>%
  janitor::clean_names() %>%
  dplyr::select(sample_id, lat, long, identity) 

gps.points$lat = as.numeric(gps.points$lat)
gps.points$long = as.numeric(gps.points$long)

southafrica_ext = rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") %>%
  dplyr::filter(name %in% c("South Africa", "Lesotho", "eSwatini"))

# Plot GPS points on world map to check our locality data is correct 
distr_map = ggplot() +
  # Add raster layer of world map 
  geom_sf(data = southafrica_ext, alpha = 0.5, fill = "grey80") +
  # Add GPS points 
  
  # ggrepel::geom_text_repel(
  #   data = gps.points,
  #   aes(x = long, y = lat, label = sample_id),  # replace `id` with your sample ID column
  #   size = 2.5,
  #   color = "grey15",
  #   max.overlaps = 50,   # adjust as needed
  #   box.padding = 0.25,
  #   point.padding = 0.1,
  #   segment.color = "grey85"
  # ) +
  
  geom_point(
    data = gps.points, 
    aes(x = long, y = lat, fill = identity), 
    size = 2,
    shape = 21,
    color = "black",
    alpha = 0.75
  ) +
  scale_fill_manual(values = c(
    "gold",
    "red",
    "forestgreen",
    "blue",
    "lightblue"
  )) +
  
  # Set world map CRS 
  coord_sf(
    crs = 4326,
    xlim = c(16, 28),      
    ylim = c(-35, -28),
    expand = FALSE
  ) + 
  xlab("Longitude") + 
  ylab("Latitude") +
  #ggtitle(expression(italic("Orachrysops niobe") * ", South Africa")) +
  ggspatial::annotation_scale(
    location = "br",          # 'bl' = bottom left
    style = "ticks",
    width_hint = 0.2
  ) +
  # Add north arrow
  ggspatial::annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.175, "in"),
    pad_y = unit(0.3, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  ) +
  theme_classic() +
  theme(legend.position = "none")

distr_map

# ggsave("figures/distr_map.png", distr_map, width = 10, dpi=400,
#        height = 5, units = "in")
# ggsave("figures/distr_map.svg", distr_map, width = 7, dpi=400,
#        height = 7, units = "in")

combo.plot = gridExtra::grid.arrange(pca.ggplot, distr_map)

# ggsave("figures/pca_and_map.png", combo.plot, width = 10, dpi=400,
#        height = 9, units = "in")
# ggsave("figures/pca_and_map.svg", combo.plot, width = 7, dpi=400,
#        height = 7, units = "in")


#####################################################################################
# END
#####################################################################################